import Foundation
#if canImport(CryptoKit)
import CryptoKit
#else
import Crypto
#endif

/// The public parameters that turn a passphrase into an identity (FORMAT.md §9.6).
/// They travel in the `.pqid`, so the identity can be rebuilt on any Mac.
struct IdentityKDF: Equatable, Sendable {
    let cost: Argon2id.Cost
    /// 16 random bytes, chosen when the identity is created.
    let salt: [UInt8]
    /// The identity also needs a key file (SECURITY.md D17).
    let requiresKeyFile: Bool

    /// Within the window a `.pqid` may declare (`IdentityFormat.kdf…Range`).
    var isAccepted: Bool {
        IdentityFormat.kdfOpsLimitRange.contains(cost.opsLimit)
            && IdentityFormat.kdfMemLimitRange.contains(cost.memLimit)
            && salt.count == IdentityFormat.kdfSaltSize
    }
}

/// The passphrase behind an identity: 7 to 10 distinct words from the EFF large
/// wordlist, generated by Chotam (SECURITY.md D17).
///
/// Anyone with your `.pqid` can test guesses offline, forever, so the passphrase is
/// never chosen by the user. Seven random words are about 90 bits. When typed back in
/// (to unlock, or on a new Mac), case and spacing don't matter: the words are
/// canonicalised to lowercase and joined by single spaces before Argon2id.
public enum IdentityPassphrase {
    public static let defaultWordCount = IdentityFormat.defaultPassphraseWords
    public static let wordCountRange = IdentityFormat.passphraseWordRange

    /// A new passphrase: distinct EFF words from the CSPRNG, separated by spaces.
    ///
    /// It is a `String` because the app has to show it once, to be written down.
    /// Strings can't be wiped (SECURITY.md §7.3): drop it as soon as it's been shown.
    public static func generate(wordCount: Int = defaultWordCount) throws(IdentityError) -> String {
        guard wordCountRange.contains(wordCount) else { throw .invalidPassphrase }
        do {
            return try PassphraseGenerator.generate(wordCount: wordCount)
        } catch {
            throw .unexpected
        }
    }

    /// Whether `typed` has the shape of an identity passphrase: 7–10 distinct EFF
    /// words. Says nothing about whether it's the *right* one.
    public static func isWellFormed(_ typed: String) -> Bool {
        canonical(typed) != nil
    }

    /// The canonical UTF-8 bytes Argon2id receives, in a locked buffer that's wiped
    /// when released. Nil if `typed` isn't 7–10 distinct EFF words.
    static func canonical(_ typed: String) -> SecretBuffer? {
        guard let lookup = Wordlist.lookup else { return nil }
        // EFF words are lowercase ASCII (four contain a hyphen). Anything else is
        // not a word, so it fails the lookup below.
        let lowered = typed.precomposedStringWithCanonicalMapping.lowercased()
        let words = lowered.split(whereSeparator: \.isWhitespace)
        guard wordCountRange.contains(words.count),
              Set(words).count == words.count,
              words.allSatisfy({ lookup.contains(String($0)) })
        else { return nil }

        let length = words.reduce(words.count - 1) { $0 + $1.utf8.count }
        let buffer = SecretBuffer(count: length)
        buffer.withUnsafeMutableBytes { out in
            var offset = 0
            for (index, word) in words.enumerated() {
                if index > 0 {
                    out[offset] = UInt8(ascii: " ")
                    offset += 1
                }
                for byte in word.utf8 {
                    out[offset] = byte
                    offset += 1
                }
            }
        }
        return buffer
    }
}

/// The private keys of an identity, rebuilt in memory from its passphrase.
struct DerivedKeys {
    let xwing: XWingMLKEM768X25519.PrivateKey
    let mldsa: MLDSA65.PrivateKey
    let ed25519: Curve25519.Signing.PrivateKey
    /// Encrypts and authenticates this identity's contacts file (FORMAT.md §10).
    let contactsKey: SymmetricKey

    /// Whether these are the keys `identity` advertises.
    func match(_ identity: PublicIdentity) -> Bool {
        [UInt8](xwing.publicKey.rawRepresentation) == identity.encryptionKeyBytes
            && [UInt8](mldsa.publicKey.rawRepresentation) == identity.mldsaKeyBytes
            && [UInt8](ed25519.publicKey.rawRepresentation) == identity.ed25519KeyBytes
    }
}

/// Passphrase (+ optional key file) → identity keys (FORMAT.md §9.6).
///
/// ```
/// master = Argon2id(canonical passphrase, salt, opsLimit, memLimit)         32 bytes
/// ikm    = master                                                           no key file
///        = master ‖ SHA-256("Chotam v1 key file" ‖ key file contents)       with one
/// seed_x = HKDF-SHA256(ikm, salt, "Chotam v1 identity X-Wing seed",    32)
/// seed_m = HKDF-SHA256(ikm, salt, "Chotam v1 identity ML-DSA-65 seed", 32)
/// seed_e = HKDF-SHA256(ikm, salt, "Chotam v1 identity Ed25519 seed",   32)
/// k_c    = HKDF-SHA256(ikm, salt, "Chotam v1 contacts key",            32)
/// ```
///
/// Distinct HKDF labels make the four outputs independent: the keys never share
/// material, and knowing one reveals nothing about the others.
enum IdentityDerivation {
    static func derive(
        passphrase: SecretBuffer, kdf: IdentityKDF, keyFileDigest: [UInt8]?
    ) throws -> DerivedKeys {
        guard kdf.isAccepted, (keyFileDigest != nil) == kdf.requiresKeyFile else {
            throw CoreFailure(.unexpected)
        }
        let master = try Argon2id.derive(secret: passphrase, salt: kdf.salt, cost: kdf.cost)

        // The IKM is built in a locked buffer, then handed to CryptoKit, which zeroes
        // its own copy when released. Every intermediate below is a SymmetricKey or
        // a SecretBuffer, so nothing secret lingers in a Swift array.
        let ikmLength = IdentityFormat.seedSize + (keyFileDigest?.count ?? 0)
        let ikmBuffer = SecretBuffer(count: ikmLength)
        ikmBuffer.withUnsafeMutableBytes { out in
            master.withUnsafeBytes { out.copyMemory(from: $0) }
            if let keyFileDigest {
                keyFileDigest.withUnsafeBytes {
                    UnsafeMutableRawBufferPointer(rebasing: out[IdentityFormat.seedSize...]).copyMemory(from: $0)
                }
            }
        }
        let ikm = ikmBuffer.symmetricKey

        func expand(_ info: [UInt8]) -> SymmetricKey {
            HKDF<SHA256>.deriveKey(
                inputKeyMaterial: ikm, salt: kdf.salt, info: info, outputByteCount: IdentityFormat.seedSize)
        }
        // The seeds go straight from CryptoKit's storage into the key constructors,
        // without a copy we'd have to wipe.
        do {
            let xwing = try expand(IdentityFormat.xwingSeedInfo).withUnsafeBytes {
                try XWingMLKEM768X25519.PrivateKey(seedRepresentation: $0, publicKey: nil)
            }
            let mldsa = try expand(IdentityFormat.mldsaSeedInfo).withUnsafeBytes {
                try MLDSA65.PrivateKey(seedRepresentation: $0, publicKey: nil)
            }
            let ed25519 = try expand(IdentityFormat.ed25519SeedInfo).withUnsafeBytes {
                try Curve25519.Signing.PrivateKey(rawRepresentation: $0)
            }
            return DerivedKeys(
                xwing: xwing, mldsa: mldsa, ed25519: ed25519,
                contactsKey: expand(IdentityFormat.contactsKeyInfo))
        } catch {
            throw CoreFailure(.unexpected)
        }
    }

    /// `SHA-256("Chotam v1 key file" ‖ contents)`, streamed, so a large key file is
    /// never held in memory. The file can be anything (a photo, random bytes); it
    /// must not be empty. Lose it, and the identity is lost too.
    static func keyFileDigest(_ url: URL) throws(IdentityError) -> [UInt8] {
        do {
            let source = try InputFile(opening: url)
            defer { source.close() }
            var hash = SHA256()
            hash.update(data: IdentityFormat.keyFileLabel)
            var total = 0
            while true {
                guard var piece = try source.handle.read(upToCount: 1 << 20), !piece.isEmpty else { break }
                hash.update(data: piece)
                total += piece.count
                Wipe.data(&piece)
            }
            guard total > 0 else { throw IdentityError.keyFileUnusable }
            return Array(hash.finalize())
        } catch let error as IdentityError {
            throw error
        } catch {
            throw .keyFileUnusable
        }
    }
}
