/// Fixed sizes and labels for identities (FORMAT.md §6.1, §9 and §10).
enum IdentityFormat {
    // Key sizes. X-Wing (draft-connolly-cfrg-xwing-kem): ML-KEM-768 encapsulation key
    // (1184) ‖ X25519 public key (32). ML-DSA-65: FIPS 204. Ed25519: RFC 8032. Tests
    // assert these against the SDK.
    static let xwingPublicKeySize = 1216
    static let mlkem768EncodedVectorSize = 1152  // the part of the ML-KEM key that holds coefficients
    static let mldsa65PublicKeySize = 1952
    static let ed25519PublicKeySize = 32
    static let mldsa65SignatureSize = FormatV1.mldsa65SignatureSize
    static let ed25519SignatureSize = 64
    /// A hybrid signature: Ed25519 (64) ‖ ML-DSA-65 (3309). Both must verify.
    static let hybridSignatureSize = ed25519SignatureSize + mldsa65SignatureSize
    static let seedSize = 32

    // Domain labels. Each hash, signature or KDF input starts with its own label, so a
    // value computed for one purpose can never be mistaken for another.
    static let encryptionKeyIDLabel = Array("Chotam v1 encryption key id".utf8)
    static let signingKeyIDLabel = Array("Chotam v1 signing key id".utf8)
    static let fingerprintLabel = Array("Chotam v1 identity fingerprint".utf8)
    static let selfSignatureLabel = Array("Chotam v1 identity signature".utf8)
    static let keyFileLabel = Array("Chotam v1 key file".utf8)
    static let xwingSeedInfo = Array("Chotam v1 identity X-Wing seed".utf8)
    static let mldsaSeedInfo = Array("Chotam v1 identity ML-DSA-65 seed".utf8)
    static let ed25519SeedInfo = Array("Chotam v1 identity Ed25519 seed".utf8)
    static let contactsKeyInfo = Array("Chotam v1 contacts key".utf8)

    // Fingerprint: 160 bits = 32 Crockford base32 characters, shown as 8 groups of 4.
    // Grover's algorithm makes a second preimage cost about 2^80 (SECURITY.md D5).
    static let fingerprintBytes = 20
    static let fingerprintGroupLength = 4

    // Passphrase-derived identity (FORMAT.md §9.6, SECURITY.md D17).
    /// `1` = Argon2id v1.3 through libsodium's `crypto_pwhash` (parallelism 1).
    static let kdfArgon2id: UInt8 = 1
    static let kdfParallelism: UInt8 = 1
    static let kdfFlagKeyFile: UInt8 = 0x01
    static let kdfSaltSize = FormatV1.argon2SaltSize  // 16: libsodium's fixed salt size
    /// What a new identity uses: 1 GiB, 8 passes (estimated 2–3 s on Apple Silicon;
    /// `DerivationTests.testDefaultCostTiming` prints the real figure).
    static let defaultKDFCost = Argon2id.Cost(opsLimit: 8, memLimit: 1 << 30)
    /// What a `.pqid` may declare. Bounds the work a substituted `.pqid` can cause
    /// at unlock, and refuses a trivially cheap derivation.
    static let kdfOpsLimitRange: ClosedRange<UInt64> = 3...16
    static let kdfMemLimitRange: ClosedRange<UInt64> = (256 << 20)...(2 << 30)
    /// The cheapest cost accepted. Tests use it to stay fast.
    static let minimumKDFCost = Argon2id.Cost(opsLimit: 3, memLimit: 256 << 20)

    // Passphrase: words from the EFF large wordlist, generated by Chotam.
    static let passphraseWordRange = 7...10
    static let defaultPassphraseWords = 7

    // .pqid v1 (FORMAT.md §9)
    static let pqidMagic = Array("CHOTAMID".utf8)
    static let pqidVersion: UInt16 = 1
    static let maxNameBytes = 64
    static let maxExtensionsBytes = 1024
    /// Extension types with this bit set must be understood, or the `.pqid` is refused.
    static let criticalExtensionBit: UInt16 = 0x8000
    /// KDF block: algorithm, flags, opsLimit, memLimit, parallelism, salt.
    static let kdfBlockSize = 1 + 1 + 8 + 8 + 1 + kdfSaltSize
    /// Everything but the name and the extensions.
    static let pqidFixedSize =
        8 + 2 + 2 + xwingPublicKeySize + 2 + mldsa65PublicKeySize + 2 + ed25519PublicKeySize
        + kdfBlockSize + 1 + 2 + 2 + hybridSignatureSize
    static let pqidMaxSize = pqidFixedSize + maxNameBytes + maxExtensionsBytes
    /// Hard caps, checked before anything is decoded: a hostile input can't make
    /// the parser allocate or hash much.
    static let pqidMaxFileSize = 8 * 1024
    static let pqidMaxStringLength = 12 * 1024

    // Files Chotam keeps in its own folder (FORMAT.md §10). Nothing secret.
    static let identityFileName = "identity.pqid"
    static let contactsFileName = "contacts.chotam"
    // Contacts file v1: encrypted and authenticated with the contacts key.
    static let contactsMagic = Array("CHOTAMCF".utf8)
    static let contactsVersion: UInt16 = 1
    static let contactsHeaderSize = 8 + 2 + 32 + 12
    static let maxContacts = 500
    static let contactsMaxFileSize = 4 << 20
}
